---
blueteam_password: "password123"
# scoring_ip: # uncomment only when we know the scoring IP, otherwise skip
backup_dir: "/usr/share/fonts/roboto-mono"
quarantine: "/usr/share/fonts/quar-mono"

packet_users:
  - harold
  - francis
  - williams

