---

- name: "SECTION | 3.1 | Configure Network Devices"
  ansible.builtin.import_tasks:
    file: 3.1.yml
  when: section_3_1

- name: "SECTION | 3.2 | Configure Network Kernel Modules"
  ansible.builtin.import_tasks:
    file: 3.2.yml
  when: section_3_2

- name: "SECTION | 3.3 | Configure Network Kernel Parameters"
  ansible.builtin.import_tasks:
    file: 3.3.yml
  when: 
    - section_3_3 
    - not system_is_container