---
- name: Check if service is in services file
  # Use block rescue for error handling
  block:
    - name: "Is {{ item.name }} a base service?"
      # Checks to see if the service name is present in the service baseline
      ansible.builtin.lineinfile:
        dest: /tmp/service_baseline.txt
        line: "{{ item.name }}"
        state: present
      check_mode: yes
      register: service_loop
      # loop automatically changes variables and outputs changed, we want OK output when service is found, so force not changed
      changed_when: false
      # This msg is outputted when the service is not found in the baseline file, fail when it is present
      failed_when: service_loop.msg == "line added"
      # no_log: true
  rescue:
    # Behavior when fail is thrown, add service name to bottom of servicediff.txt
    - name: "{{ item.name }} is not a base service... auditing"
      ansible.builtin.lineinfile:
        dest: "{{ backup_dir }}/servicediff.txt"
        line: "{{ item.name }}"
        insertafter: EOFs