---

- name: POST | Gather the package facts after remediation
  ansible.builtin.package_facts:
    manager: auto

- name: POST | Update sysctl
  ansible.builtin.template:
    src: "etc/sysctl.d/{{ item }}.j2"
    dest: "/etc/sysctl.d/{{ item }}"
    owner: root
    group: root
    mode: 'go-rwx'
  loop:
    - 60-kernel_sysctl.conf
    - 60-disable_ipv6.conf
    - 60-netipv4_sysctl.conf
    - 60-netipv6_sysctl.conf
  when:
    - sysctl_update
    - not system_is_container
    - "'procps-ng' in ansible_facts.packages"

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: POST | reboot system if changes require it and not skipped
  ansible.builtin.debug:
    msg: "Warning!! changes have been made that require a reboot to be implemented but skip reboot was set - Can affect compliance check results"
  changed_when: true