---

# for 1.5
- name: "PRELIM | AUDIT | Check systemd coredump"
  ansible.builtin.stat:
    path: /etc/systemd/coredump.conf
  register: prelim_systemd_coredump

# for 1.8
- name: "PRELIM | Discover Gnome Desktop Environment"
  tags:
    - always
  ansible.builtin.stat:
    path: /usr/share/gnome/gnome-version.xml
  register: prelim_gnome_present

# for 3.1
- name: "PRELIM | AUDIT | Wireless adapter pre-requisites"
  when:
    - not system_is_container
  tags:
    - always
  block:
    - name: "PRELIM | AUDIT | Discover is wirelss adapter on system"
      ansible.builtin.command: find /sys/class/net/*/ -type d -name wireless
      register: discover_wireless_adapters
      changed_when: false
      failed_when: discover_wireless_adapters.rc not in [ 0, 1 ]

    - name: "PRELIM | PATCH | Install Network-Manager | if wireless adapter present"
      when:
        - discover_wireless_adapters.rc == 0
        - "'NetworkManager' not in ansible_facts.packages"
      ansible.builtin.package:
        name: NetworkManager
        state: present

- name: "PRELIM | AUDIT | Gather UID 0 accounts other than root"
  ansible.builtin.shell: "cat /etc/passwd | awk -F: '($3 == 0 && $1 != \"root\") {i++;print $1 } END {exit i}'"
  changed_when: false
  check_mode: false
  register: prelim_uid_zero_accounts_except_root

