---
- name: Assert Variables
  hosts: all
  tasks:
    - name: Assert Variables
      fail:
        msg: "You must define ansible_control_ip in group_vars/main.yaml"
      when: ansible_control_ip is not defined
  tags:
    - never
    - initial
    - setup

- name: Initial Run
  hosts: all
  become: yes
  roles: 
    - setup # create blue user, adds key to user, creates backup directory, installs common packages
  tags:
    - never
    - initial
    - setup
  vars_prompt:
  - name: blueteam_password
    prompt: Enter blueteam user password 
    private: true
    confirm: true
    # unsafe: true # If using special characters such as { or %, uncomment this line.
    salt_size: 7
