---
- name: Assert Variables
  hosts: all
  tasks:
    - name: Assert Variables
      fail:
        msg: "You must define ansible_control_ip in inventory.ini"
      when: ansible_control_ip is not defined
  tags:
    - never
    - deploy
    - setup

# Creates blueteam user as admin on localhost, creates SSH keypair
# Clones all scripts that need to be copied over
- name: Setup Ansible Controller
  hosts: localhost
  become: yes
  roles:
    - setup-controller
  tags:
    - never
    - deploy
    - setup

# create blueteam user on Ansible-managed hosts, adds key to user
# creates backup directory, installs common core packages for firewall and backups
- name: Setup Hosts
  hosts: all
  become: yes
  roles: 
    - setup-hosts-core
  tags:
    - never
    - deploy
    - setup
    - setup-hosts
  vars_prompt:
  - name: blueteam_password
    prompt: Set blueteam user's password
    private: true
    confirm: true
    # unsafe: true # If using special characters such as { or %, uncomment this line.
    salt_size: 7

- name: Take Backups
  hosts: all
  become: yes
  roles:
    - backups
  tags:
    - never
    - deploy
    - backups
  ignore_errors: true

- name: Verify pacman
  hosts: all
  become: yes
  roles:
    - verify-pacman
  tags:
    - never
    - verify-pacman

- name: Setup Firewall
  hosts: all
  become: yes
  roles:
    - firewall # copy current firewall rules, run lite if no scoring ip, otherwise harden that shit
  tags:
    - never
    - deploy
    - firewall

# Install useful packages and runs yara setup script
- name: Setup Hosts
  hosts: all
  become: yes
  roles: 
    - setup-hosts-other
  tags:
    - never
    - deploy
    - setup
    - setup-hosts

- name: Reinstall Package Manager
  hosts: all
  become: true
  roles:
    - reinstall-pacman
  tags:
    - never
    - reinstall-pacman
  ignore_errors: true

- name: Set Up Password Manager Server
  hosts: all
  become: yes
  roles:
    - password-manager-server
  tags:
    - never
    - deploy
    - password-manager
  ignore_errors: true

- name: Setup Password Manager Client
  hosts: all
  become: yes
  roles:
    - password-manager-client
  tags:
    - never
    - deploy
    - password-manager
  ignore_errors: true

- name: Setup Birdsnest Server
  hosts: all
  become: yes
  roles:
    - birdsnest
  tags:
    - never
    - deploy
    - birdsnest
  #ignore_errors: true

- name: Setup Birdsnest Owlet Client
  hosts: all
  become: yes
  roles:
    - birdsnest-owlet
  tags:
    - never
    - deploy
    - owlet
  #ignore_errors: true

- name: Setup Birdsnest Magpie Client
  hosts: all
  become: yes
  roles:
    - birdsnest-magpie
  tags:
    - never
    - deploy
    - magpie
  #ignore_errors: true

- name: Audit System
  hosts: all
  become: yes
  roles: 
    - audit 
  tags:
    - never
    - deploy
    - audit
  ignore_errors: true

- name: Harden OS
  hosts: all
  become: yes
  roles:
    - harden_os
  tags:
    - never
    - deploy
    - harden
  ignore_errors: true

- name: Harden WordPress
  hosts: wordpress_server
  become: yes
  roles:
    - wordpress
  tags:
    - never
    - wordpress
    - deploy

# - name: Harden NGINX
#   hosts: nginx_server
#   become: yes
#   roles:
#     - nginx
#   tags:
#     - never
#     - nginx
#     - deploy

# - name: Harden Kube Controller
#   hosts: kubemgr
#   become: yes
#   roles:
#     - kube
#   tags:
#     - never
#     - kube
#     - deploy

- name: Finishing tasks (keep talking)
  hosts: all
  become: yes
  roles:
    - finishing_tasks
  tags:
    - never
    - deploy
    - finish

#If not installed, add deploy tag to falco. If not, just modify compose file for sidekick with Grafana IP

- name: Deploy Falco
  hosts: all
  become: yes
  roles:
    - falco
  tags:
    - never
    - falco
    
- name: Deploy Falco Sidekick
  hosts: all
  become: yes
  roles:
    - falco-sidekick
  tags:
    - never
    - deploy
    - falco
    - falcosidekick