---
- name: Assert Variables
  hosts: all
  tasks:
    - name: Assert Variables
      fail:
        msg: "You must define ansible_control_ip in group_vars/main.yaml"
      when: ansible_control_ip is not defined
  tags:
    - never
    - deploy
    - setup

- name: Generate SSH key combination
  hosts: localhost
  become: false
  roles:
    - pre-setup
  tags:
    - never
    - setup

- name: Initial Run
  hosts: all
  become: yes
  roles: 
    - setup # create blue user, adds key to user, creates backup directory, installs common packages
  tags:
    - never
    - setup
  vars_prompt:
  - name: blueteam_password
    prompt: Enter blueteam user password 
    private: true
    confirm: true
    # unsafe: true # If using special characters such as { or %, uncomment this line.
    salt_size: 7

- name: Take Backups
  hosts: all
  become: yes
  roles:
    - backups
  tags:
    - never
    - deploy
    - backups

- name: Reinstall Package Manager
  hosts: all
  become: true
  roles:
    - reinstall-pacman
  tags:
    - never
    - deploy
    - reinstall-pacman

- name: Setup Firewall
  hosts: all
  become: yes
  roles:
    - firewall # copy current firewall rules, run lite if no scoring ip, otherwise harden that shit
  tags:
    - never
    - deploy
    - firewall

- name: Audit System
  hosts: all
  become: yes
  roles: 
    - audit 
  tags:
    - never
    - deploy
    - audit

# - name: Harden NGINX
#   hosts: nginx_server
#   become: yes
#   roles:
#     - nginx
#   tags:
#     - never
#     - nginx
#     - deploy

# - name: Harden Kube Controller
#   hosts: kubemgr
#   become: yes
#   roles:
#     - kube
#   tags:
#     - never
#     - kube
#     - deploy

- name: Setup Password Manager
  hosts: all
  become: yes
  roles:
    - passwordManagerServer
  tags:
    - never
    - deploy
    - password-manager

- name: Setup Password Manager Client
  hosts: all
  become: yes
  roles:
    - passwordManagerClient
  tags:
    - never
    - deploy
    - password-manager

- name: Harden OS
  hosts: all
  become: yes
  roles:
    - harden_os
  tags:
    - never
    - deploy
    - harden

- name: Finish me off
  hosts: all
  become: yes
  roles:
    - finishing_tasks
  tags:
    - never
    - deploy
    - finish