---
- name: Setup Firewall
  hosts: all
  roles:
    - firewall
  tags:
    - initial
    - firewall

- name: Modify Users
  hosts: all
  roles:
    - users
  tags:
    - initial
    - users

- name: Harden SSH
  hosts: all
  roles:
    - ssh
  tags:
    - never
    - initial
    - ssh

- name: Install Wazuh Manager
  hosts: Manager
  roles:
    - wazuh-manager
  tags:
    - initial
    - logging

    # - backups
    # - downloads
    # - users
    # - hardening