---
- name: Run initial Setup
  hosts: all
  roles: 
    - setup 
  tags:
    - initial
    - setup

- name: Setup PFSense Firewall
  hosts: router
  roles:
    - firewall
  tags:
    - initial
    - firewall

- name: Modify Users
  hosts: all
  roles:
    - users
  tags:
    - initial
    - users

- name: run audit 
  hosts: all
  roles: 
    - audit
  tags:
    - initial
    - audit

- name: Harden SSH
  hosts: all
  roles:
    - ssh
  tags:
    - never
    - initial
    - ssh

- name: Install Wazuh Manager
  hosts: manager
  roles:
    - wazuh-manager
  tags:
    - initial
    - logging