---
- name: Run initial Setup
  hosts: linux
  become: yes
  roles: 
    - setup 
  tags:
    - initial
    - setup

- name: Setup PFSense Firewall
  hosts: router
  become: yes
  roles:
    - pfsense
  tags:
    - initial
    - pfsense

- name: Modify Users
  hosts: linux
  become: yes
  roles:
    - users
  tags:
    - initial
    - users

- name: run audit 
  hosts: linux
  become: yes
  roles: 
    - audit
  tags:
    - initial
    - audit

- name: Install Wazuh Manager
  hosts: manager
  become: yes
  roles:
    - wazuh-manager
  tags:
    - initial
    - logging

- name: Setup logging 
  hosts: linux
  become: yes
  roles:
    - logging
  tags: 
    - initial
    - logging