[all]
192.168.1.61
192.168.1.54

[logging]
None

[kube]

[kubemgr]

[all:vars]
controller_in_scope_allow_ip=""
important_files_for_backup=[]
ansible_connection=ssh
ssh_port=22
backup_dir="/usr/share/fonts/roboto-mono"
quarantine="/usr/share/fonts/quar-mono"
audit_dir="/opt/audit"
password_manager_ip="10.1.1.12" #REPLACE
siem_ip="" #REPLACE
stabvest_controller_ip="192.168.1.51"
ansible_control_ip="192.168.1.51" 
firewall_logging=true
siem="Grafana"

[_ccdc-endevour_192_168_1_54]
192.168.1.54

[_ccdc-endevour_192_168_1_54:vars]
ansible_user="ccdc"
ansible_password="ccdc"
ansible_become_password="ccdc"
scored_ports_tcp=['22', '1716']
scored_ports_udp=['1716', '5353', '46890', '51093']

[solaris]
192.168.1.61

[solaris:vars]
ansible_user="ccdc"
ansible_password="Password-123456"
ansible_become_password="Password-123456"
scored_ports_tcp=['22', '1716']
scored_ports_udp=['1716', '5353', '46890', '51093']
