[all]
# TODO add ips

[logging]
# TODO add Grafana IP

[kube]

[kubemgr]

[all:vars]
controller_in_scope_allow_ip=""
important_file_for_backup=[]
ansible_connection=ssh
ssh_port=22
backup_dir="/usr/share/fonts/roboto-mono"
quarantine="/usr/share/fonts/quar-mono"
audit_dir="/opt/audit"
password_manager_ip="" # TODO replace with Password Manager IP
siem_ip="" # TODO replace with Grafana IP
stabvest_controller_ip="" # TODO replace with Stabvest IP
ansible_control_ip="" # TODO Replace with Ansible Control IP WITH VPN
firewall_logging=true
siem="Wazuh"
ansible_user="ccdc"
ansible_password="ccdc" #REPLACE
ansible_become_password="ccdc"  #REPLACE

[teleport]


[teleport:vars]
scored_ports_tcp=['443', '3021', '3022']
scored_ports_udp=[]

[wordpress]


[wordpress:vars]
scored_ports_tcp=['80', '443', '8000', '8080', '8443']
scored_ports_udp=[]

[gitea]


[gitea:vars]
scored_ports_tcp=['80', '443', '3000', '8000', '8080', '8443']
scored_ports_udp=[]

[semaphore]


[semaphore:vars]
scored_ports_tcp=['80', '443', '3000', '8000', '8080', '8443']
scored_ports_udp=[]

[kiosk]


[kiosk:vars]
scored_ports_tcp=['80', '443', '8000', '8080', '8443']
scored_ports_udp=[]