[all]
172.16.1.10
172.16.1.53
172.16.1.12
172.16.1.52
10.1.1.10
10.1.1.11
10.1.1.12

[logging]
172.16.1.53

[kube]

[kubemgr]

[alpine]

[alpine:vars]
ansible_become_method=doas

[all:vars]
controller_in_scope_allow_ip=""
ansible_connection=ssh
ssh_port=22
backup_dir="/usr/share/fonts/roboto-mono"
quarantine="/usr/share/fonts/quar-mono"
audit_dir="/opt/audit"
password_manager_ip="172.16.1.11"
siem_ip="172.16.1.11"
stabvest_controller_ip="192.168.1.51"
ansible_control_ip="192.168.1.51" 
firewall_logging=true
siem="Grafana"

[Debian_new-test-deb11_172_16_1_10]
172.16.1.10

[Debian_new-test-deb11_172_16_1_10:vars]
ansible_user="ccdc"
ansible_password="ccdc"
ansible_become_password="ccdc"
scored_ports_tcp=['80', '22']
scored_ports_udp=[]

[Ubuntu_new-test-ubu22_172_16_1_11]
172.16.1.53

[Ubuntu_new-test-ubu22_172_16_1_11:vars]
ansible_user="ccdc"
ansible_password="ccdc"
ansible_become_password="ccdc"
scored_ports_tcp=['3000', '22']
scored_ports_udp=[]

[Rocky_new-test-rocky8_172_16_1_12]
172.16.1.12

[Rocky_new-test-rocky8_172_16_1_12:vars]
ansible_user="ccdc"
ansible_password="ccdc"
ansible_become_password="ccdc"
scored_ports_tcp=['22']
scored_ports_udp=[]

[Rocky_new-test-rocky8_172_16_1_52]
172.16.1.52

[Rocky_new-test-rocky8_172_16_1_52:vars]
ansible_user="ccdc"
ansible_password="ccdc"
ansible_become_password="ccdc"
scored_ports_tcp=['22']
scored_ports_udp=[]

[Debian_new-test-deb12_10_1_1_10]
10.1.1.10

[Debian_new-test-deb12_10_1_1_10:vars]
ansible_user="ccdc"
ansible_password="ccdc"
ansible_become_password="ccdc"
scored_ports_tcp=['22']
scored_ports_udp=[]

[Ubuntu_new-test-ubu24_10_1_1_11]
10.1.1.11

[Ubuntu_new-test-ubu24_10_1_1_11:vars]
ansible_user="ccdc"
ansible_password="ccdc"
ansible_become_password="ccdc"
scored_ports_tcp=['80', '22']
scored_ports_udp=[]

[Rocky_new-test-rocky9_10_1_1_12]
10.1.1.12

[Rocky_new-test-rocky9_10_1_1_12:vars]
ansible_user="ccdc"
ansible_password="ccdc"
ansible_become_password="ccdc"
scored_ports_tcp=['22']
scored_ports_udp=[]
