[all]
10.1.1.10

[logging]
None

[kube]

[kubemgr]

[all:vars]
controller_in_scope_allow_ip=""
important_files_for_backup=[]
ansible_connection=ssh
ssh_port=22
backup_dir="/usr/share/fonts/roboto-mono"
quarantine="/usr/share/fonts/quar-mono"
audit_dir="/opt/audit"
password_manager_ip="10.1.1.12" #REPLACE
siem_ip="" #REPLACE
stabvest_controller_ip="192.168.1.51"
ansible_control_ip="192.168.1.51" 
firewall_logging=true
siem="Grafana"

[solaris]
10.1.1.10

[solaris:vars]
ansible_user="ccdc"
ansible_password="ccdc"
ansible_become_password="ccdc"
scored_ports_tcp=['22']
scored_ports_udp=[]
