---

- name: "SECTION | 5.1 | Configure SSH Server"
  ansible.builtin.import_tasks:
    file: 5.1.yml
  when:
    - section_5_1
    - "'openssh-server' in ansible_facts.packages"

- name: "SECTION | 5.2 | Configure privilege escalation"
  ansible.builtin.import_tasks:
    file: 5.2.yml
  when: section_5_2

- name: "SECTION | 5.3 | Configure: PAM software packages, authselect, pam_faillock module, pam_pwquality module, pam_pwhistory module, pam_unix module"
  ansible.builtin.import_tasks:
    file: 5.3.yml
  when: section_5_3

- name: "SECTION | 5.4 | Configure: shadow password suite parameters, root and system accounts and environment, user default environment"
  ansible.builtin.import_tasks:
    file: 5.4.yml
  when: section_5_4
