---
- name: WORDPRESS HARDEN | Disable file editing
  blockinfile:
    dest:  "{{ wp_path }}/wp-config.php"
    create: no
    backup: yes
    insertbefore: ".*stop editing.*"
    state: present
    content: |
      define('DISALLOW_FILE_EDIT', true);
      define('FS_METHOD', 'direct');

- name: WORDPRESS HARDEN | Block wp-config.php
  blockinfile:
    dest:  "{{ wp_path }}/.htaccess"
    create: false
    insertbefore: "# BEGIN WordPress"
    state: present
    content: |
      <Files wp-config.php>
        order allow,deny
        deny from all
      </Files>

- name: WORDPRESS HARDEN | Block dot files and xmlrpc
  blockinfile:
    dest:  "{{ wp_path }}/.htaccess"
    create: no
    backup: yes
    insertbefore: "# BEGIN WordPress"
    state: present
    content: |
      <Files ~ "^.*\.([Hh][Tt][Aa])">
        order allow,deny
        deny from all
      </Files>

      <Files xmlrpc.php>
        order allow,deny
        deny from all
      </Files>

- name: WORDPRESS HARDEN | Block access to wp-includes
  blockinfile:
    dest:  "{{ wp_path }}/.htaccess"
    create: no
    backup: yes
    insertbefore: "# BEGIN WordPress"
    state: present
    content: |
      <IfModule mod_rewrite.c>
        RewriteEngine On
        RewriteBase /
        RewriteRule ^wp-admin/includes/ - [F,L]
        RewriteRule !^wp-includes/ - [S=3]
        RewriteRule ^wp-includes/[^/]+\.php$ - [F,L]
        RewriteRule ^wp-includes/js/tinymce/langs/.+\.php - [F,L]
        RewriteRule ^wp-includes/theme-compat/ - [F,L]
      </IfModule>

- name: WORDPRESS HARDEN | Prevent username enumeration and script injection
  blockinfile:
    dest:  "{{ wp_path }}/.htaccess"
    create: no
    backup: yes
    insertbefore: "# BEGIN WordPress"
    state: present
    content: |
      RewriteCond %{QUERY_STRING} author=d
      RewriteRule ^ /? [L,R=301]

      Options +FollowSymLinks
      RewriteEngine On
      RewriteCond %{QUERY_STRING} (<|%3C).*script.*(>|%3E) [NC,OR]
      RewriteCond %{QUERY_STRING} GLOBALS(=|[|%[0-9A-Z]{0,2}) [OR]
      RewriteCond %{QUERY_STRING} _REQUEST(=|[|%[0-9A-Z]{0,2})
      RewriteRule ^(.*)$ index.php [F,L]
  
- name: WORDPRESS HARDEN | Disable PHP execution in uploads directory.
  blockinfile:
    dest:  "{{ wp_path }}/{{ wp_uploads_dir | default('wp-content/uploads') }}/.htaccess"
    create: yes
    backup: yes
    marker: "# {mark} ANSIBLE MANAGED BLOCK: Kill PHP Execution"
    insertafter: EOF
    state: present
    content: |
      <Files ~ "\.ph(?:p[345]?|t|tml)$">
         deny from all
      </Files>

- name: WORDPRESS HARDEN | Update Wordpress file ownership
  file:
    path: "{{ wp_path }}"
    recurse: yes
    owner: www-data
    group: www-data

- name: WORDPRESS HARDEN | Update Wordpress file and directory permissions
  shell: "{{ item }}"
  with_items:
    - "find {{ wp_path }} -type d -exec chmod
      755 {} \\;"
    - "find {{ wp_path }} -type f -exec chmod 
      644 {} \\;"

- name: WORDPRESS HARDEN | Check for WP-CLI
  command: which wp
  register: wp_cli_path
  changed_when: false
  ignore_errors: true

- name: WORDPRESS HARDEN | Verify WordPress core file integrity (WP-CLI)
  shell: >
    wp --allow-root --path={{ wp_path }} core verify-checksums 2>&1
  register: core_checksum
  when: wp_cli_path.rc == 0
  changed_when: false
  ignore_errors: true

- name: "WORDPRESS HARDEN | Report core checksum results (WP-CLI)"
  debug:
    msg: "{{ core_checksum.stdout_lines }}"
  when:
    - wp_cli_path.rc == 0
    - core_checksum is not skipped