---
- name: WORDPRESS | Backup wp-config.php before changes
  copy:
    src: "{{ wp_path }}/wp-config.php"
    dest: "{{ wp_path }}/wp-config.php.bak"
    remote_src: true
    owner: root
    mode: "0600"
  ignore_errors: true

- name: WORDPRESS | Backup .htaccess before changes
  copy:
    src: "{{ wp_path }}/.htaccess"
    dest: "{{ wp_path }}/.htaccess.bak"
    remote_src: true
    owner: root
    mode: "0600"
  ignore_errors: true

- name: WORDPRESS | Run Wordpress Harden
  import_tasks: harden.yml

- name: WORDPRESS | Run Wordpress Audit
  import_tasks: audit.yml