---

- name: "1.1.2.1 | AUDIT | Ensure /tmp is a separate partition"
  block:
    - name: "Check if /tmp is a separate partition"
      ansible.builtin.command: mount | grep -w '/tmp'
      register: tmp_mount_check
      failed_when: false
      changed_when: false

    - name: "Warn if /tmp is not a separate partition"
      ansible.builtin.debug:
        msg: >
          "Warning!! /tmp is not mounted as a separate partition. This is a manual task."
      when: tmp_mount_check.rc != 0

    - name: "Log a warning count for /tmp partition"
      ansible.builtin.import_tasks:
        file: warning_facts.yml
      when: tmp_mount_check.rc != 0
  when: ansible_facts['os_family'] in ['Debian', 'RedHat', 'BSD', 'Suse']