call each sections main here
have this get executed by the main playbook

reinstall core services (pam, ssh, etc.)

- name: "CIS Benchmark | prelims"
  ansible.builtin.import_tasks:
    file: prelim.yaml

- name: "CIS Benchmark | section 1"
  ansible.builtin.import_tasks:
    file: section1/main.yaml

- name: "CIS Benchmark | section 3"
  ansible.builtin.import_tasks:
    file: section3/main.yaml

- name: "CIS Benchmark | section 5"
  ansible.builtin.import_tasks:
    file: section5/main.yaml

- name: "CIS Benchmark | section 6"
  ansible.builtin.import_tasks:
    file: section6/main.yaml

- name: "CIS Benchmark | section 7"
  ansible.builtin.import_tasks:
    file: section7/main.yaml

- name: ClamAV
  ansible.builtin.import_tasks: 
    file: clamav.yml
