---

- name: PRELIM | PATCH | Find all sudoers files.
  when:
    - ubtu22cis_rule_5_2_4 or
      ubtu22cis_rule_5_2_5
  tags: always
  ansible.builtin.shell: "find /etc/sudoers /etc/sudoers.d/ -type f ! -name '*~' ! -name '*.*'"
  changed_when: false
  failed_when: false
  check_mode: false
  register: prelim_sudoers_files