- name: Copy over Falco helm script
  ansible.builtin.copy:
    src: falco_setup.sh
    dest: /var/tmp/get_helm.sh
    owner: blueteam
    group: blueteam
    mode: '0700'

- name: Copy over Falco configuration file
  ansible.builtin.copy:
    src: falco.yaml
    dest: /etc/falco-config.yaml
    owner: root
    group: root
    mode: '0644'

- name: Copy over Falco rules files
  ansible.builtin.copy:
    src: falco_rules.yaml
    dest: /etc/falco-rules.yaml
    owner: root
    group: root
    mode: '0644'

- name: Load Wazuh Manager IP into Falco config file
  ansible.builtin.replace:
    path: /etc/falco-config.yaml
    regexp: '<WAZUH_MANAGER_IP>'  # Match the placeholder
    replace: "{{ wazuh_manager_ip }}"  # Replace with the variable value

- name: Copy over bash script to install Helm + Falco
  ansible.builtin.copy:
    src: falco_setup.sh
    dest: /var/tmp/install_helm.sh
    owner: blueteam
    group: blueteam
    mode: '0700'