---
# allow ssh port
# allow score check ports in (INPUT chain, dest port)
# allow score check ports out (OUTPUT chain, src port)
# allow dns 
# allow https & http

- name: Backup Rules
  ansible.builtin.shell: "iptables-save >> /etc/iptables_rules.v4.pre_lite"

- name: Accept policies
  iptables:
    chain: "{{ item }}"
    policy: ACCEPT
  with_items:
    - "INPUT"
    - "OUTPUT"

- name: Flush rules
  iptables:
    flush: yes
    chain: "{{ item.chain }}"
  with_items:
    - { chain: INPUT }
    - { chain: OUTPUT }

- name: Allow SSH 
  iptables: 
    chain: INPUT
    protocol: tcp
    destination_ports: 
      - "22"
    jump: ACCEPT

- name: Allow HTTP + HTTPS out
  iptables:
    chain: OUTPUT
    source_port: "{{ item }}"
    protocol: tcp
    jump: ACCEPT
  with_items:
    - "80"
    - "443"

- name: Allow DNS
  iptables: 
    chain: OUTPUT
    protocol: udp
    destination_port: 53
    jump: ACCEPT

- name: Allow scored services ports in (TCP)
  iptables:
    chain: INPUT
    destination_port: "{{ item }}"
    jump: ACCEPT
    protocol: tcp
  loop: "{{ scored_ports_tcp }}"
  ignore_errors: yes

- name: Allow scored services ports in (UDP)
  iptables:
    chain: INPUT
    destination_port: "{{ item }}"
    jump: ACCEPT
    protocol: udp
  loop: "{{ scored_ports_udp }}"
  ignore_errors: yes

- name: Allow related and established connections
  iptables:
    chain: INPUT
    ctstate: RELATED,ESTABLISHED
    jump: ACCEPT

- name: Allow related and established connections
  iptables:
    chain: OUTPUT
    ctstate: RELATED,ESTABLISHED
    jump: ACCEPT

- name: Allow loopback
  iptables:
    chain: INPUT
    in_interface: lo
    jump: ACCEPT

- name: Allow loopback
  iptables:
    chain: OUTPUT
    out_interface: lo
    jump: ACCEPT

- name: Block everything else
  iptables:
    chain: "{{ item.chain }}"
    policy: DROP
  with_items:
    - { chain: INPUT }
    - { chain: OUTPUT }
