---

- name: "6.1.1 | PATCH | Ensure AIDE is installed"
  block:
    - name: "6.1.1"
      ansible.builtin.package:
        name: "{{ aide_packages }}"
        state: present
        update_cache: true
      register: discovered_aide_pkg_added

    - name: "6.1.1 | Recapture packages"
      ansible.builtin.package_facts:
        manager: auto
      when: discovered_aide_pkg_added.skipped is not defined

    - name: "6.1.1 | Check file exists"
      ansible.builtin.stat:
        path: "{{ aide_db_file }}"
      register: discovered_aide_db_file

    - name: "6.1.1 | Check current db file age"
      ansible.builtin.find:
        path: "{{ aide_db_file | dirname }}"
        pattern: "{{ aide_db_file | basename }}"
        age: "{{ aide_db_file_age }}"
      register: discovered_aide_db_age
      when: discovered_aide_db_file.stat.exists

    - name: "6.1.1 | Configure AIDE"
      block:
        - name: "6.1.1 | Build AIDE DB"
          ansible.builtin.command: "{{ aide_initiate_command }}"
          changed_when: true

        - name: "6.1.1 | Wait for file before continuing"
          ansible.builtin.wait_for:
            path: /var/lib/aide/aide.db.new.gz

        - name: "6.1.1 | copy AIDE DB"
          ansible.builtin.copy:
            src: /var/lib/aide/aide.db.new.gz
            dest: /var/lib/aide/aide.db.gz
            remote_src: true
            mode: 'ug-wx,o-rwx'
      when:
        - not ansible_check_mode
        - not discovered_aide_db_file.stat.exists or
          (discovered_aide_db_age.files | length > 0) or
          aide_db_recreate
  when:
    - rule_6_1_1
    - config_aide

- name: "6.1.2 | PATCH | Ensure filesystem integrity is regularly checked"
  block:
    - name: "6.1.2"
      ansible.builtin.cron:
        name: Run AIDE integrity check
        cron_file: "{{ aide_cron['cron_file'] }}"
        user: "{{ aide_cron['cron_user'] }}"
        minute: "{{ aide_cron['aide_minute'] | default('0') }}"
        hour: "{{ aide_cron['aide_hour'] | default('5') }}"
        day: "{{ aide_cron['aide_day'] | default('*') }}"
        month: "{{ aide_cron['aide_month'] | default('*') }}"
        weekday: "{{ aide_cron['aide_weekday'] | default('*') }}"
        job: "{{ aide_cron['aide_job'] }}"
      when: aide_scan == "cron"

    - name: "6.1.2 | aide service"
      ansible.builtin.systemd_service:
        name: aidecheck.service
        enabled: true
      when: aide_scan == "timer"

    - name: "6.1.2 | aide service"
      ansible.builtin.systemd_service:
        name: aidecheck.timer
        state: started
        enabled: true
      when: aide_scan == "timer"
  when: rule_6_1_2

- name: "6.1.3 | PATCH | Ensure cryptographic mechanisms are used to protect the integrity of audit tools"
  ansible.builtin.blockinfile:
    path: /etc/aide.conf
    marker: "# {mark} Audit tools - CIS benchmark - Ansible-lockdown"
    block: |
      /usr/sbin/auditctl p+i+n+u+g+s+b+acl+xattrs+sha512
      /usr/sbin/auditd p+i+n+u+g+s+b+acl+xattrs+sha512
      /usr/sbin/augenrules p+i+n+u+g+s+b+acl+xattrs+sha512
      /usr/sbin/aureport p+i+n+u+g+s+b+acl+xattrs+sha512
      /usr/sbin/ausearch p+i+n+u+g+s+b+acl+xattrs+sha512
      /usr/sbin/autrace p+i+n+u+g+s+b+acl+xattrs+sha512
    validate: aide -D --config %s
  when: rule_6_1_3