
---
- name: Install curl
  ansible.builtin.package:
    name: curl
    state: present
    
- name: Download and import Wazuh GPG key
  ansible.builtin.command: 
    cmd: "curl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH | gpg --keyring gnupg-ring:/usr/share/keyrings/wazuh.gpg --import"
  when: ansible_os_family == "Debian"

- name: Set permissions for the Wazuh GPG key
  ansible.builtin.file:
    path: /usr/share/keyrings/wazuh.gpg
    mode: '0644'
  when: ansible_os_family == "Debian"

- name: Add Wazuh repository to sources list
  ansible.builtin.command: 
    cmd: echo "deb [signed-by=/usr/share/keyrings/wazuh.gpg] https://packages.wazuh.com/4.x/apt/ stable main" | tee -a /etc/apt/sources.list.d/wazuh.list
  when: ansible_os_family == "Debian"

- name: Update apt package index
  ansible.builtin.apt:
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Install Wazuh agent 
  ansible.builtin.shell: 
    cmd: apt-get install -y wazuh-agent 
  when: ansible_os_family == "Debian"

- name: Import Wazuh GPG key
  rpm_key:
    state: present
    key: https://packages.wazuh.com/key/GPG-KEY-WAZUH
  when: ansible_os_family == "RedHat" 

- name: Create Wazuh repository file
  copy:
    dest: /etc/yum.repos.d/wazuh.repo
    content: |
      [wazuh]
      gpgcheck=1
      gpgkey=https://packages.wazuh.com/key/GPG-KEY-WAZUH
      enabled=1
      name=EL-$releasever - Wazuh
      baseurl=https://packages.wazuh.com/4.x/yum/
      protect=1
  notify: Refresh YUM cache
  when: ansible_os_family == "RedHat" 

- name: Refresh YUM cache
  ansible.builtin.yum:
    update_cache: yes
  when: ansible_os_family == "RedHat"
  
- name: Install Wazuh Agent
  yum:
    name: wazuh-agent
    state: present
  when: ansible_os_family == "RedHat"

- name: Enroll agent using manager IP address
  replace:
    path: /var/ossec/etc/ossec.conf
    regexp: 'MANAGER_IP'
    replace: "{{ manager_ip }}"

- name: Install YARA and git
  ansible.builtin.package:
    name: 
      - yara
      - git
    state: present

- name: Create /opt/yara/rules directory
  ansible.builtin.file:
    path: /opt/yara/rules
    state: directory
    mode: '0755'

- name: Copy over compiled YARA rules
  ansible.builtin.copy:
    src: compiled.linux
    dest: /opt/yara/rules/compiled.linux
    owner: root
    group: wazuh
    mode: '0660'

- name: Copy over YARA active response script
  ansible.builtin.copy: 
    src: yara.sh
    dest: /var/ossec/active-response/bin/yara.sh
    owner: root
    group: wazuh 
    mode: '0750'

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Enable Wazuh agent service
  ansible.builtin.systemd:
    name: wazuh-agent
    enabled: yes

- name: Start Wazuh agent service
  ansible.builtin.systemd:
    name: wazuh-agent
    state: started
