---
stabvest_allow_ips_web:   # IPs that the Nginx proxy will allow to webserver web (frontend) endpoints. Set to your jumpboxes' IPs/range.
  - 127.0.0.1
  - 172.16.0.0/12
stabvest_allow_ips_agent: # IPs that the Nginx proxy will allow to webserver agent (backend) endpoints. Set to the inscope IPs/ranges.
  - 127.0.0.1
  - 10.0.0.0/8
stabvest_host: "{{ ansible_default_ipv4.address }}" # Public URL of server used for linking and certs. note: is NOT used for starting the server listener (that is always 0.0.0.0)
stabvest_port: 8000       # External port to listen on
webhook_url: "https://discord.com/api/webhooks/1445146908808188065/1xkiXfsL7ie8i04rGxdMu6nnnzJsVtj188VbHtZT5oBNJIoOYV5VP8lpI-mJhzeNYuYD" # Discord webhook url (empty string if none)
agent_auth_tokens:        # Registration tokens that agents use for the initial connection - must be copied to the agent deploy ansible!
  testtoken:              # token value
    added_by: "default"   # leave as is
webgui_users:             # Users that can log into the website frontend
  admin:                  # username
    password: "admin"     # password
    role: "admin"         # role - admin, analyst, or guest
  analyst:
    password: "analyst"
    role: "analyst"
  guest:
    password: "guest"
    role: "guest"

#####
# Variables below this line are not critical and can likely be ignored
#####

# Deploy vars
stabvest_deploy_dir: "/stabvest_server"
stabvest_gunicorn_workers: 1 # per replica
stabvest_webserver_replicas: 3
stabvest_proxy_container: "nginx:1.28.2"
stabvest_database_image: "postgres:18.3"
stabvest_python_container: "alpine:3.19"

# Derived values can still be overridden if needed
public_url: "https://{{ stabvest_host }}:{{ stabvest_port }}"
logfile: "log.txt"

# server config.json values
secret_key: "{{ lookup('ansible.builtin.password', '/dev/null length=32 chars=ascii_letters,digits,special') }}"
stale_time: 300
default_webhook_sleep_time: 0.25
max_webhook_msg_per_minute: 50
create_test_data: false
database_creds: "birdsnest:birdsnestpwd"
database_location: "database:5432"
database_db: "birdsnestdb"
authconfig_strict_ip: false
authconfig_strict_user: false
authconfig_create_incident: false
authconfig_log_attempt_successful: true