---
- name: Copy over honeypot setup script
  ansible.builtin.copy:
    src: gouda.sh
    dest: /home/blueteam
    owner: blueteam
    group: blueteam
    mode: '0755'

- name: Run honeypot setup script and delete it
  ansible.builtin.shell: bash /home/blueteam/gouda.sh && rm /home/blueteam/gouda.sh