- name: Create blueteam user
  hosts: all
  become: yes
  vars:
    groups_to_check:
      - blueteam
      - wheel
      - sudo
      - adm
  
  tasks:
    - name: Create blueteam group
      group:
        name: blueteam
        state: present

    - name: Check which groups exist
      command: getent group {{ item }}
      register: group_check
      ignore_errors: yes
      loop: "{{ groups_to_check }}"

    - name: Set the list of existing groups
      set_fact:
        existing_groups: "{{ existing_groups | default([]) + [item.item] }}"
      when: item.rc == 0
      loop: "{{ group_check.results }}"

    - name: Create blueteam user
      user:
        name: blueteam
        state: present
        groups: "{{ existing_groups | join(',') }}"
        append: yes
        shell: /bin/bash
        password: "{{ blueteam_password | password_hash('sha512') }}"

- name: Load user list and set passwords
  hosts: all
  become: yes

  tasks:
    - name: Load user list from file
      slurp:
        src: users.txt
      register: user_list_file

    - name: Parse user list and set passwords
      set_fact:
        users: "{{ user_list_file['content'] | b64decode | splitlines | map('split', ' ') | map('first') | list }}"
        passwords: "{{ user_list_file['content'] | b64decode | splitlines | map('split', ' ') | map('last') | list }}"

    - name: Generate and set passwords for each user
      user:
        name: "{{ item.0 }}"
        password: "{{ item.1 | password_hash('sha512') }}"
      loop: "{{ users | zip(passwords) | list }}"
