---
- name: Create blueteam group
  group:
    name: blueteam
    state: present

- name: Check which groups exist
  command: getent group {{ item }}
  register: group_check
  ignore_errors: true
  loop: 
    - blueteam
    - wheel
    - sudo
    - adm

- name: Set the list of existing groups
  set_fact:
    existing_groups: "{{ existing_groups | default([]) + [item.item] }}"
  when: item.rc == 0
  loop: "{{ group_check.results }}"

- name: Create blueteam user
  user:
    name: blueteam
    state: present
    groups: "{{ existing_groups | join(',') }}"
    append: yes
    shell: /bin/bash
    password: "{{ blueteam_password | password_hash('sha512') }}"

- name: set user_data fact
  set_fact:
    user_data: "{{ lookup('file', 'users.txt').splitlines() }}"

- name: Generate and set passwords for each user
  user:
    name: "{{ item.split(' ')[0] }}"
    password: "{{ item.split(' ')[1] | password_hash('sha512') }}"
  loop: "{{ user_data }}"