- name: Create blueteam user
  hosts: all
  become: yes
  vars:
    groups:
      - blueteam
      - wheel
      - sudo
      - adm
  
  tasks:
    - name: Create blueteam group
      group:
        name: blueteam
        state: present

    - name: Check which groups exist
      command: getent group {{ item }}
      register: group_check
      ignore_errors: yes
      loop: "{{ groups }}"

  - name: Set the list of existing groups
    set_facts:
      existing_groups: "{{ existing_groups | default([]) + [item.item] }}"
    when: item.rc == 0
    loop: "{{ group_check.results }}"

    - name: Create blueteam user
      user:
        name: blueteam
        state: present
        groups: "{{ existing_groups | join(',') }}"
        append: yes
        shell: /bin/bash
        password: "{{ blueteam_password | password_hash('sha512') }}"

- name: Load user list from file
  hosts: all
  become: yes
  vars:
    users: "{{ lookup('file', 'users.txt').splitlines() }}"
  
  tasks:
    - name: Generate and set passwords for each user
      user:
        name: "{{ item }}"
        password: "{{ lookup('password', '/dev/null', length=20, chars=ascii_letters) | password_hash('sha512') }}"
      loop: "{{ users }}"
