---
- name: Create blueteam group
  group:
    name: blueteam
    state: present

- name: Create blueteam user
  user:
    name: blueteam
    state: present
    groups: "blueteam sudo wheel adm"
    append: yes
    shell: /bin/bash
  ignore_errors: true

- name: Read /etc/passwd and filter users with valid shells
  ansible.builtin.shell: |
    awk -F: '$7 ~ /^\/bin\// && $1 !~ /^(whiteteam|grayteam|blackteam)$/ {print $1}' /etc/passwd
  register: user_list

#todo remove users that arent legit

- name: Generate and set passwords for each user
  user:
    name: "{{ item }}"
    password: "{{ lookup('ansible.builtin.password', 'length=12') }}"
  loop: "{{ user_list.stdout_lines }}"
