---
# change this to find all users with a shell (look for any shell in /etc/shells) and exclude blueteam
- name: Find users with /bin shell except white/gray/black team
  ansible.builtin.shell: |
    awk -F: '$7 ~ /^\/bin\// && $1 !~ /^(whiteteam|grayteam|blackteam)$/ {print $1}' /etc/passwd
  register: user_list

- name: Generate and set passwords/Display generated passwords
  ansible.builtin.block:
  - name: Generate and set passwords
    ansible.builtin.user:
      name: "{{ item }}"
      password: "{{ lookup('ansible.builtin.password', 'length=12') }}"
    loop: "{{ user_list.stdout_lines }}"
    register: user_password
    loop_control: 
      lable: "{{ item }}"

  - name: Display generated passwords
    ansible.builtin.debug:
      sg: "User: {{ item.item }}, Password: {{ item.password }}"
    loop: "{{ user_password.results }}"

    # output every user and password combo to /tmp file, copy that file to ansible controller, then remove it

#TODO once we install bin/redd well change /sbin/nologin to /bin/redd
- name: Deactivate each user by setting their shell to /sbin/nologin
  ansible.builtin.user:
    name: "{{ item }}"
    shell: /sbin/nologin
  loop: "{{ deactivate_user_list.stdout_lines }}"

- name: Move all ssh authorized keys to quarantine
  ansible.builtin.shell: |
    mv /home/{{ item }}/.ssh/authorized_keys {{ quarantine }}/authorized_keys_{{ item }}
  loop: "{{ user_list.stdout_lines }}"
  