---

- name: "3.1.1 | PATCH | Ensure IPv6 status is identified"
  block:
    - name: "3.1.1 | Replace ipv6.disable if it exists"
      ansible.builtin.replace:
        path: /etc/default/grub
        regexp: '^(GRUB_CMDLINE_LINUX=.*)\bipv6\.disable=\d\b(.*$)'
        replace: '\1ipv6.disable=1\2'
      register: discovered_ipv6disable_replaced
      when: ipv6_disable == 'grub'
      notify: Grub update
      ignore_errors: yes

    - name: "3.1.1 | Check grub cmdline linux"
      ansible.builtin.shell: grep "GRUB_CMDLINE_LINUX=" /etc/default/grub | cut -f2 -d'"'
      changed_when: false
      failed_when: false
      check_mode: false
      register: discovered_grub_cmdline_settings

    - name: "3.1.1 | Insert ipv6.disable if it doesn't exist"
      ansible.builtin.lineinfile:
        path: /etc/default/grub
        regexp: '^(GRUB_CMDLINE_LINUX=".*)"$'
        line: '\1 ipv6.disable=1"'
        backrefs: true
      when:
        - ipv6_disable == 'grub'
        - discovered_ipv6disable_replaced is not changed
        - "'ipv6.disable' not in discovered_grub_cmdline_settings.stdout"
      notify: Grub update
      ignore_errors: yes

    - name: "3.1.1 | Remove net.ipv6.conf.all.disable_ipv6"
      ansible.builtin.template:
        src: "{{ ansible_dir }}/roles/harden_os/ubu22/templates/{{ item }}.j2"
        dest: "/{{ item }}"
        owner: root
        group: root
        mode: 'g-wx,o-rwx'
      loop:
        - etc/sysctl.d/60-disable_ipv6.conf
      when: ipv6_disable == 'sysctl'
      notify: Flush ipv6 route table
      ignore_errors: yes
  when:
    - rule_3_1_1
    - not ipv6_required

- name: "3.1.2 | PATCH | Ensure wireless interfaces are disabled"
  block:
    - name: "3.1.2 | Check for network-manager tool"
      ansible.builtin.command: nmcli radio wifi
      changed_when: false
      failed_when: false
      check_mode: false
      register: discovered_wifi_status
      when: "'network-manager' in ansible_facts.packages"

    - name: "3.1.2 | Disable wireless if network-manager installed"
      ansible.builtin.command: nmcli radio all off
      changed_when: discovered_nmcli_radio_off.rc == 0
      register: discovered_nmcli_radio_off
      when:
        - "'network-manager' in ansible_facts.packages"
        - "'enabled' in discovered_wifi_status.stdout"

    - name: "3.1.2 | Warn about wireless if network-manager not installed"
      ansible.builtin.debug:
        msg: "Warning!! You need to disable wireless interfaces manually since network-manager is not installed"
      when: "'network-manager' not in ansible_facts.packages"
  when:
    - rule_3_1_2
    - prelim_wireless_adapters_exist

- name: "3.1.3 | PATCH | Ensure bluetooth services are not in use"
  ansible.builtin.package:
    name: bluez
    state: absent
  when: rule_3_1_3
