---

# The CIS Control wants IPv6 disabled if not in use.
# We are using the ipv6_required to specify if you have IPv6 in use
- name: "3.1.1 | PATCH | Ensure IPv6 status is identified"
  when:
    - not ipv6_required
  block:
    - name: "3.1.1 | refresh"
      ansible.builtin.set_fact:
        rhel9cis_sysctl_update: true
        rhel9cis_flush_ipv6_route: true

    - name: "3.1.1 | disable"
      ansible.builtin.debug:
        msg: "Control being set via Handler 'update sysctl' which writes to /etc/sysctl.d/60-disable_ipv6.conf"

- name: "3.1.2 | PATCH | Ensure wireless interfaces are disabled"
  when:
    - discover_wireless_adapters.rc == 0
  block:
    - name: "3.1.2 | Check for network-manager tool"
      when: "'network-manager' in ansible_facts.packages"
      ansible.builtin.command: nmcli radio wifi
      changed_when: false
      failed_when: false
      check_mode: false
      register: discovered_wifi_status

    - name: "3.1.2 | Disable wireless if network-manager installed"
      when:
        - "'network-manager' in ansible_facts.packages"
        - "'enabled' in discovered_wifi_status.stdout"
      ansible.builtin.command: nmcli radio all off
      changed_when: discovered_nmcli_radio_off.rc == 0
      register: discovered_nmcli_radio_off

    - name: "3.1.2 | Warn about wireless if network-manager not installed"
      when: "'network-manager' not in ansible_facts.packages"
      ansible.builtin.debug:
        msg: "Warning!! You need to disable wireless interfaces manually since network-manager is not installed"

- name: "3.1.3 | PATCH | Ensure bluetooth services are not in use"
  ansible.builtin.package:
    name: bluez
    state: absent
