- name: Copy over Falcosidekick Docker compose file
  ansible.builtin.copy:
    src: docker-compose.yml
    dest: /home/blueteam/docker-compose.yml
    owner: blueteam
    group: blueteam
    mode: 0644

- name: Deploy the stack
  community.docker.docker_compose_v2:
    project_src: "/home/blueteam"
    state: present
    pull: always