---

- name: "1.7.1 | PATCH | Ensure message of the day is configured properly"
  ansible.builtin.template:
    src: "{{ ansible_dir }}/tasks/rhel9/templates/etc/motd.j2"
    dest: /etc/motd
    owner: root
    group: root
    mode: 'u-x,go-wx'
  when: rule_1_7_1

- name: "1.7.2 | PATCH | Ensure local login warning banner is configured properly"
  ansible.builtin.template:
    src: "{{ ansible_dir }}/tasks/rhel9/templates/etc/issue.j2"
    dest: /etc/issue
    owner: root
    group: root
    mode: 'go-wx'
  when: rule_1_7_2

- name: "1.7.3 | PATCH | Ensure remote login warning banner is configured properly"
  ansible.builtin.template:
    src: "{{ ansible_dir }}/tasks/rhel9/templates/etc/issue.net.j2"
    dest: /etc/issue.net
    owner: root
    group: root
    mode: 'go-wx'
  when: rule_1_7_3

- name: "1.7.4 | PATCH | Ensure permissions on /etc/motd are configured"
  ansible.builtin.file:
    path: /etc/motd
    owner: root
    group: root
    mode: 'go-wx'
  when: rule_1_7_4

- name: "1.7.5 | PATCH | Ensure permissions on /etc/issue are configured"
  ansible.builtin.file:
    path: /etc/issue
    owner: root
    group: root
    mode: 'go-wx'
  when: rule_1_7_5

- name: "1.7.6 | PATCH | Ensure permissions on /etc/issue.net are configured"
  ansible.builtin.file:
    path: /etc/issue.net
    owner: root
    group: root
    mode: 'go-wx'
  when: rule_1_7_6