---

- name: "2.4.1.1 | PATCH | Ensure cron daemon is enabled"
  when: rule_2_4_1_1
  ansible.builtin.service:
    name: crond
    enabled: true

- name: "2.4.1.2 | PATCH | Ensure permissions on /etc/crontab are configured"
  when: rule_2_4_1_2
  ansible.builtin.file:
    path: /etc/crontab
    owner: root
    group: root
    mode: 'og-rwx'

- name: "2.4.1.3 | PATCH | Ensure permissions on /etc/cron.hourly are configured"
  when: rule_2_4_1_3
  ansible.builtin.file:
    path: /etc/cron.hourly
    state: directory
    owner: root
    group: root
    mode: 'og-rwx'

- name: "2.4.1.4 | PATCH | Ensure permissions on /etc/cron.daily are configured"
  when: rule_2_4_1_4
  ansible.builtin.file:
    path: /etc/cron.daily
    state: directory
    owner: root
    group: root
    mode: 'og-rwx'

- name: "2.4.1.5 | PATCH | Ensure permissions on /etc/cron.weekly are configured"
  when: rule_2_4_1_5
  ansible.builtin.file:
    path: /etc/cron.weekly
    state: directory
    owner: root
    group: root
    mode: 'og-rwx'

- name: "2.4.1.6 | PATCH | Ensure permissions on /etc/cron.monthly are configured"
  when: rule_2_4_1_6
  ansible.builtin.file:
    path: /etc/cron.monthly
    state: directory
    owner: root
    group: root
    mode: 'og-rwx'

- name: "2.4.1.7 | PATCH | Ensure permissions on /etc/cron.d are configured"
  when: rule_2_4_1_7
  ansible.builtin.file:
    path: /etc/cron.d
    state: directory
    owner: root
    group: root
    mode: 'og-rwx'

- name: "2.4.1.8 | PATCH | Ensure crontab is restricted to authorized users"
  when: rule_2_4_1_8
  block:
    - name: "2.4.1.8 | Remove cron.deny"
      ansible.builtin.file:
        path: /etc/cron.deny
        state: absent

    - name: "2.4.1.8 | Check if cron.allow exists"
      ansible.builtin.stat:
        path: "/etc/cron.allow"
      register: discovered_cron_allow_state

    - name: "2.4.1.8 | Ensure cron.allow is restricted to authorized users"
      ansible.builtin.file:
        path: /etc/cron.allow
        state: '{{ "file" if discovered_cron_allow_state.stat.exists else "touch" }}'
        owner: root
        group: root
        mode: 'u-x,g-wx,o-rwx'

- name: "2.4.2.1 | PATCH | Ensure at is restricted to authorized users"
  when: rule_2_4_2_1
  block:
    - name: "2.4.2.1 | Remove at.deny"
      ansible.builtin.file:
        path: /etc/at.deny
        state: absent

    - name: "2.4.2.1 | Check if at.allow exists"
      ansible.builtin.stat:
        path: "/etc/at.allow"
      register: discovered_at_allow_state

    - name: "2.4.2.1 | Ensure at.allow is restricted to authorized users"
      ansible.builtin.file:
        path: /etc/at.allow
        state: '{{ "file" if discovered_at_allow_state.stat.exists else "touch" }}'
        owner: root
        group: root
        mode: 'u-x,g-wx,o-rwx'