---

- name: Update_Initramfs
  ansible.builtin.command: update-initramfs -u
  changed_when: true
  notify: Set_reboot_required

- name: Grub update
  ansible.builtin.command: update-grub
  changed_when: true
  failed_when: false
  notify: Set_reboot_required

- name: Restart timeservice
  ansible.builtin.systemd:
    name: "{{ ubtu22cis_time_sync_tool }}"
    state: restarted

- name: Reload systemctl
  ansible.builtin.systemd:
    daemon_reload: true

- name: Update dconf
  ansible.builtin.command: dconf update
  changed_when: true
  failed_when: false

- name: Restart postfix
  ansible.builtin.service:
    name: postfix
    state: restarted

- name: Restart syslog service
  ansible.builtin.systemd:
    name: "{{ ubtu22cis_syslog_service }}"
    state: restarted

- name: Restart journald
  ansible.builtin.systemd:
    name: systemd-journald
    state: restarted

- name: Restart exim4
  ansible.builtin.systemd:
    name: exim4
    state: restarted

- name: Restart firewalld
  ansible.builtin.systemd:
    name: firewalld.service
    state: restarted

- name: Restart fail2ban
  ansible.builtin.systemd:
    name: fail2ban.service
    state: restarted

- name: Restart sshd
  ansible.builtin.systemd:
    name: sshd.service
    state: restarted

- name: Restart clamav-daemon
  ansible.builtin.systemd:
    name: clamav-daemon.service
    state: restarted

- name: Restart system
  ansible.builtin.reboot:
  when:
    - system_reboot_enabled | bool

- name: Restart auditd
  when: discovered_audit_rules_updated is defined
  ansible.builtin.command: service auditd restart  # noqa command-instead-of-module
  changed_when: true

- name: Reload ufw
  community.general.ufw:
    state: reloaded

- name: Pam_auth_update_pwunix
  ansible.builtin.command: pam-auth-update --enable pam_unix
  changed_when: true

- name: Pam_auth_update_pwfaillock
  ansible.builtin.command: pam-auth-update --enable faillock
  changed_when: true

- name: Pam_auth_update_pwfaillock_notify
  ansible.builtin.command: pam-auth-update --enable faillock_notify
  changed_when: true

- name: Pam_auth_update_pwquality
  ansible.builtin.command: pam-auth-update --enable pwquality
  changed_when: true

- name: Pam_auth_update_pwhistory
  ansible.builtin.command: pam-auth-update --enable pwhistory
  changed_when: true

- name: Flush ipv4 route table
  ansible.posix.sysctl:
    name: net.ipv4.route.flush
    value: '1'
    sysctl_set: true
  when: ansible_facts.virtualization_type != "docker"

- name: Flush ipv6 route table
  ansible.posix.sysctl:
    name: net.ipv6.route.flush
    value: '1'
    sysctl_set: true
  when:
    - ansible_facts.virtualization_type != "docker"
    - ipv6_required

- name: Set_reboot_required
  ansible.builtin.set_fact:
    change_requires_reboot: true