- name: Check if manager already installed
  ansible.builtin.stat:
    path: /opt/ccdc-password-manager/docker-compose.yml
  register: manager_exists

- name: Setup manager
  block:
    - name: Create directory
      ansible.builtin.file:
        path: "/opt/ccdc-password-manager"
        owner: blueteam
        group: blueteam
        state: directory
        mode: 0755

    - name: Copy Image
      ansible.builtin.copy:
        src: password-manager-latest.tar.gz
        dest: /opt/ccdc-password-manager/password-manager-latest.tar.gz

    - name: Copy Compose File
      ansible.builtin.copy:
        src: docker-compose.yml
        dest: /opt/ccdc-password-manager/docker-compose.yml

    - name: Copy starting clients
      ansible.builtin.copy:
        src: starting_clients.txt
        dest: /opt/ccdc-password-manager/starting_clients.txt
        mode: '0644'

    - name: Copy setup script
      ansible.builtin.copy:
        src: setup-password-manager-server.sh
        dest: /opt/ccdc-password-manager/setup-password-manager-server.sh
        mode: '0744'

    - name: Run setup script
      ansible.builtin.command: ./setup-password-manager-server.sh
      args:
        chdir: /opt/ccdc-password-manager
  when: not manager_exists.stat.exists and ansible_default_ipv4.address == password_manager_ip

- name: Get starting credentials
  block:
    - name: sleep 2 seconds to wait for creds to populate
      ansible.builtin.pause:
        seconds: 2

    - name: Read starting creds file
      ansible.builtin.slurp:
        src: /opt/ccdc-password-manager/default_credentials.txt
      register: default_creds

    - name: Decode and print starting credentials
      ansible.builtin.debug:
        msg: "Starting credentials for Password Manager: {{ default_creds.content | b64decode }}"
  when: ansible_default_ipv4.address == password_manager_ip