---
#####
# Critical vars - change these
#####

stabvest_agent_name: "apache2"    # Agent name. Must be unique per agent per host. For example, if this protects apache2, name it 'apache2'
stabvest_disarm: false            # TRUE to operate in DISARM mode (reporting only, no autofix)
stabvest_debug_print: true      
stabvest_iptables_path: "iptables" # (Linux only) path to iptables binary. Note: iptables-save should be colocated with this binary at {{ stabvest_iptables_path }}-save
stabvest_ports:     # List of ports to protect
  - 80
stabvest_services:  # List of service names to protect
  - "apache2"
#  - "httpd"
#  - "W3SVC"
stabvest_packages:  # List of packages to protect
  - "apache2"
#  - "httpd"
#  - "IIS-WebServerRole"
stabvest_service_backups: # TODO REPLACE WITH AUTO
  PathName: "C:\\\\Windows\\\\system32\\\\svchost.exe -k iissvcs"
  StartName: "localSystem"
  Dependencies: "['WAS','HTTP']"
  DisplayName: "World Wide Web Publishing Service"
  StartType: "Auto"
#stabvest_service_backups:
#  PathName: "C:\\Windows\\system32\\svchost.exe -k AxInstSVGroup"
#  StartName: "LocalSystem"
#  Dependencies: null
#  DisplayName: "ActiveX Installer (AxInstSV)"
#  StartType: "Manual"
stabvest_protected_folders: # List of folders or files to protect. For example, service content, service config, service executable, service systemd file
  - "/var/www"
  - "/usr/sbin/apache2"
  - "/etc/apache2"
  - "/lib/systemd/system/apache2.service"
#stabvest_protected_folders: ["/var/www","/usr/sbin/httpd","/etc/httpd/conf","/etc/httpd/conf.d","/etc/httpd/conf.modules.d","/etc/httpd/modules","/usr/lib/systemd/system/httpd.service"]
#stabvest_protected_folders: ['C:\\inetpub\\wwwroot']


#####
# Critical vars that should be automated safely - just confirm that they're still good
#####

stabvest_auth_token: "{{ birdsnest_token }}"  # Initial token to use for registration, found in agent_auth_tokens from main server deploy or from /web/management page
stabvest_server_url: "https://{{ birdsnest_host }}/"  # Server IP to connect to - must be in format https://{ip}:{port}/


##########
# Variables below this line are not critical and can likely be left on the default values
##########


# Ansible Deployment Vars
stabvest_agent_executable: "agent.py" 
stabvest_tester_executable: "agent_tester.py"
stabvest_include_tester: true
stabvest_service_start: true
stabvest_deploy_dir: "{{ [ (ansible_os_family == 'Windows') | ternary('C:\\stabvest', '/stabvest'), stabvest_agent_name, '' ] | path_join }}"
#stabvest_task_create: false
#stabvest_task_name: "stabvest"
#stabvest_task_interval: 300 #seconds. cron needs this to be an even minutes value (so divisible by 60)

# More Agent Config Options
stabvest_server_timeout: 5
stabvest_sleeptime: 60
stabvest_logfile: "log.txt"
stabvest_statusfile: "status.txt"
stabvest_mtu_min: 1200
stabvest_mtu_default: 1300
stabvest_mtu_max: 1514
stabvest_linux_default_ttl: 64
stabvest_agent_type: "stabvest"
stabvest_backupdir: "" # unused, just perma defaults to same dir as the agent executable