###USAGE: ansible-playbook block-ip.yml -i inventory.ini --extra-vars "ip:1.2.3.4"

- name: Block IP Address 
  hosts: linux
  become: true
  gather_facts: false 
  tasks:
    - name: Verify IP address variable is provided
      ansible.builtin.assert:
        that:
          - ip is defined
        fail_msg: "FATAL: No IP address variable provided"
        
    - name: Block inbound traffic
      ansible.builtin.iptables:
        chain: INPUT
        source: "{{ ip }}"
        jump: DROP
    
    - name: Block outbound traffic
      ansible.builtin.iptables:
        chain: OUTPUT
        source: "{{ ip }}"
        jump: DROP

