###USAGE: ansible-playbook password=change.yml -i inventory.ini --extra-vars ""

- name: Change password 
  hosts: all
  become: true
  gather_facts: false 
  tasks:
    - name: Verify user variable is provided
      ansible.builtin.assert:
        that:
          - username is defined
        fail_msg: "FATAL: No username variable provided"

    - name: Verify new_pass variable is provided
      ansible.builtin.assert:
        that:
          - new_pass is defined
        fail_msg: "FATAL: No new_pass variable provided"

    - name: Log the deployment time on the local controller
      ansible.builtin.shell: 'mkpasswd -m yescrypt " {{ new_pass }} "'
      delegate_to: localhost
      register: new_pass_hash
        
    # - name: Update user password
    #   ansible.builtin.user:
    #     name: "{{ username }}"
    #     shell: 'echo -e "{{ new_pass }}\n{{ new_pass }}"|passwd {{ username }}'

