###USAGE: ansible-playbook password=change.yml -i inventory.ini --extra-vars "username=ccdc new_pass=ccdcpass"

- name: Change password 
  hosts: all
  become: true
  gather_facts: false 
  tasks:
    - name: Verify user variable is provided
      ansible.builtin.assert:
        that:
          - username is defined
        fail_msg: "FATAL: No username variable provided"

    - name: Verify new_pass variable is provided
      ansible.builtin.assert:
        that:
          - new_pass is defined
        fail_msg: "FATAL: No new_pass variable provided"

    - name: Generate yescrypt hash for new password
      ansible.builtin.shell: 'mkpasswd -m yescrypt " {{ new_pass }} "'
      delegate_to: localhost
      register: new_pass_hash

    - name: Display the value of a simple variable
      ansible.builtin.debug:
        var: new_pass_hash.stdout
        
    - name: Change user password
      ansible.builtin.user:
        name: " {{ username }} "
        password: " {{ new_pass_hash }} "
        update_password: always
        state: present
