---
- name: Gather facts for localhost
  ansible.builtin.setup:

- name: Gather package facts
  ansible.builtin.package_facts:

- name: Install Useful Packages Debian
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "openssl"
    - "libssl-dev"
    - "automake"
    - "libtool"
    - "make"
    - "gcc"
    - "pkg-config"
    - "snoopy"
    - "lynis"
    - "jq"
    - "git"
    - "whois"
    - "gnupg"
    - "gnupg2"
  ignore_errors: true
  environment:
    DEBIAN_FRONTEND: noninteractive
    UCF_FORCE_CONFOLD: "true"
  timeout: 300
  when: ansible_facts['os_family'] == "Debian"

- name: Install Useful Packages RedHat
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "openssl"
    - "openssl-devel"
    - "automake"
    - "libtool"
    - "make"
    - "gcc"
    - "pkg-config"
    - "epel-release" # should fix snoopy and lynis
    - "snoopy"
    - "lynis"
    - "jq"
    - "git"
    - "whois"
  ignore_errors: true
  environment:
    DEBIAN_FRONTEND: noninteractive
    UCF_FORCE_CONFOLD: "true"
  timeout: 300
  when: ansible_facts['os_family'] == "RedHat"

- name: Create Yara directory
  ansible.builtin.file:
    path: /opt/yara
    state: directory
    owner: blueteam
    group: blueteam
    mode: 0755

- name: Copy yara files needed
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/opt/yara/{{ item }}"
    owner: blueteam
    group: blueteam
    mode: 0664
  with_items:
    - "Linux.zip"
    - "Multi.zip"
    - "yara-forge-rules-full.zip"
    - "yara.tar.gz"

- name: Copy Yara setup script
  ansible.builtin.copy:
    src: yara-setup.sh
    dest: /opt/yara-setup.sh
    owner: blueteam
    group: blueteam
    mode: 0744

- name: Run Yara setup script
  ansible.builtin.shell: /opt/yara-setup.sh
  ignore_errors: true

- name: Copy Falco setup script (Deb)
  ansible.builtin.copy:
    src: falco-setup-ubu.sh
    dest: /opt/falco-setup.sh
    owner: blueteam
    group: blueteam
    mode: 0744
  when: ansible_facts['os_family'] == "Debian"   

- name: Copy Falco setup script (RHEL)
  ansible.builtin.copy:
    src: falco-setup-rhel.sh
    dest: /opt/falco-setup.sh
    owner: blueteam
    group: blueteam
    mode: 0744
  when: ansible_facts['os_family'] == 'RedHat'   

- name: Run Falco setup script
  ansible.builtin.shell: /opt/falco-setup.sh
  ignore_errors: true
  
- name: Copy over Falco incubating rules
  ansible.builtin.copy:
    src: falco-incubating_rules.yaml
    dest: /etc/falco/rules.d/falco-incubating_rules.yaml
    owner: root
    group: root
    mode: 0644

- name: Copy over Falco sandbox rules
  ansible.builtin.copy:
    src: falco-sandbox_rules.yaml
    dest: /etc/falco/rules.d/falco-sandbox_rules.yaml
    owner: root
    group: root
    mode: 0644

- name: Restart falco service
  ansible.builtin.service:
    name: falco-modern-bpf
    state: restarted
  ignore_errors: true

#UNCOMMENT BELOW TO SETUP FALCO SIDEKICK (AFTER EDITING CONFIG.YAML)

- name: Copy over Falco sidekick setup script
  ansible.builtin.copy:
    src: falcosidekick-setup.sh
    dest: /opt/falcosidekick-setup.sh
    owner: blueteam
    group: blueteam
    mode: 0744

- name: Run Falco sidekick setup script
  ansible.builtin.shell: /opt/falcosidekick-setup.sh
  ignore_errors: true

- name: Move Falco Sidekick service file over
  ansible.builtin.copy:
    src: falcosidekick.service
    dest: /etc/systemd/system/falcosidekick.service
    owner: root
    group: root
    mode: 0644

- name: Move over Falco sidekick config file
  ansible.builtin.copy:
    src: falcosidekick_config.yaml
    dest: /etc/falcosidekick/config.yaml
    owner: root
    group: root
    mode: 0644

- name: Daemon Reload
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Enable Falcosidekick Service
  ansible.builtin.systemd:
    name: falcosidekick.service
    enabled: yes
    state: restarted