---
- name: Gather facts for localhost
  ansible.builtin.setup:

- name: Gather package facts
  ansible.builtin.package_facts:

- name: Install Useful Packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "openssl"
    - "libssl-dev"
    - "automake"
    - "libtool"
    - "make"
    - "gcc"
    - "pkg-config"
  ignore_errors: true

- name: Copy Yara zip file
  ansible.builtin.copy:
    src: /opt/yara.zip
    dest: /opt/yara.zip
    owner: blueteam
    group: blueteam
    mode: 0644

- name: Copy Yara setup script
  ansible.builtin.copy:
    src: yara-setup.sh
    dest: /opt/yara-setup.sh
    owner: blueteam
    group: blueteam
    mode: 0744

- name: Run Yara setup script
  ansible.builtin.shell: /opt/yara-setup.sh
  ignore_errors: true

- name: Copy Falco setup script (Deb)
  ansible.builtin.copy:
    src: falco-setup-ubu.sh
    dest: /opt/falco-setup.sh
    owner: blueteam
    group: blueteam
    mode: 0744
  when: ansible_facts['os_family'] == "Debian"   

- name: Copy Falco setup script (RHEL)
  ansible.builtin.copy:
    src: falco-setup-rhel.sh
    dest: /opt/falco-setup.sh
    owner: blueteam
    group: blueteam
    mode: 0744
  when: ansible_facts['os_family'] == 'RedHat'   

- name: Run Falco setup script
  ansible.builtin.shell: /opt/falco-setup.sh
  ignore_errors: true
  
- name: Copy over Falco incubating rules
  ansible.builtin.copy:
    src: falco-incubating_rules.yaml
    dest: /etc/falco/rules.d/falco-incubating_rules.yaml
    owner: root
    group: root
    mode: 0644

- name: Copy over Falco sandbox rules
  ansible.builtin.copy:
    src: falco-sandbox_rules.yaml
    dest: /etc/falco/rules.d/falco-sandbox_rules.yaml
    owner: root
    group: root
    mode: 0644

- name: Restart falco service
  ansible.builtin.service:
    name: falco-modern-bpf
    state: restarted