---
  
- name: "SECTION | 5.2 | Configure privilege escalation"
  when: 
    - section_5_2
    - not system_is_container
  ansible.builtin.import_tasks:
    file: 5.2.yml

- name: "SECTION | 5.3 | Configure: PAM software packages, pam-auth-update, pam_faillock module, pam_pwquality module, pam_pwhistory module, pam_unix module"
  when: 
    - section_5_3
    - not system_is_container
  ansible.builtin.import_tasks:
    file: 5.3.yml

- name: "SECTION | 5.4 | Configure: shadow password suite parameters, root and system accounts and environment, user default environment"
  when: 
    - section_5_4
    - not system_is_container
  ansible.builtin.import_tasks:
    file: 5.4.yml