---

- name: "3.3.1 | PATCH | Ensure IP forwarding is disabled"
  block:
    - name: "3.3.1 | IPv4 settings"
      ansible.posix.sysctl:
        name: net.ipv4.ip_forward
        value: '0'
        sysctl_set: true
        sysctl_file: /etc/sysctl.conf
        state: present
        reload: true
        ignoreerrors: true
      notify: Flush ipv4 route table

    - name: "3.3.1 | IPv6 settings"
      when: ipv6_disable == 'sysctl'
      ansible.posix.sysctl:
        name: net.ipv6.conf.all.forwarding
        value: '0'
        sysctl_set: true
        sysctl_file: /etc/sysctl.conf
        state: present
        reload: true
        ignoreerrors: true
      notify: Flush ipv6 route table

- name: "3.3.2 | PATCH | Ensure packet redirect sending is disabled"
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: '0'
    sysctl_set: true
    sysctl_file: /etc/sysctl.conf
    state: present
    reload: true
    ignoreerrors: true
  loop:
    - net.ipv4.conf.all.send_redirects
    - net.ipv4.conf.default.send_redirects
  notify: Flush ipv4 route table

- name: "3.3.3 | PATCH | Ensure bogus ICMP responses are ignored"
  ansible.posix.sysctl:
    name: net.ipv4.icmp_ignore_bogus_error_responses
    value: '1'
    sysctl_set: true
    sysctl_file: /etc/sysctl.conf
    state: present
    reload: true
    ignoreerrors: true
  notify: Flush ipv4 route table

- name: "3.3.4 | PATCH | Ensure broadcast ICMP requests are ignored"
  ansible.posix.sysctl:
    name: net.ipv4.icmp_echo_ignore_broadcasts
    value: '1'
    sysctl_set: true
    sysctl_file: /etc/sysctl.conf
    state: present
    reload: true
    ignoreerrors: true
  notify: Flush ipv4 route table

- name: "3.3.5 | PATCH | Ensure ICMP redirects are not accepted"
  block:
    - name: "3.3.5 | IPv4 settings"
      ansible.posix.sysctl:
        name: "{{ item }}"
        value: '0'
        sysctl_set: true
        sysctl_file: /etc/sysctl.conf
        state: present
        reload: true
        ignoreerrors: true
      loop:
        - net.ipv4.conf.all.accept_redirects
        - net.ipv4.conf.default.accept_redirects
      notify: Flush ipv4 route table

    - name: "3.3.5 | IPv6 settings"
      ansible.posix.sysctl:
        name: "{{ item }}"
        value: '0'
        sysctl_set: true
        sysctl_file: /etc/sysctl.conf
        state: present
        reload: true
        ignoreerrors: true
      when: ipv6_disable == 'sysctl'
      loop:
        - net.ipv6.conf.all.accept_redirects
        - net.ipv6.conf.default.accept_redirects
      notify: Flush ipv6 route table

- name: "3.3.6 | PATCH | Ensure secure ICMP redirects are not accepted"
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: '0'
    sysctl_set: true
    sysctl_file: /etc/sysctl.conf
    state: present
    reload: true
    ignoreerrors: true
  loop:
    - net.ipv4.conf.all.secure_redirects
    - net.ipv4.conf.default.secure_redirects
  notify: Flush ipv4 route table

- name: "3.3.7 | PATCH | Ensure Reverse Path Filtering is enabled"
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: '1'
    sysctl_set: true
    sysctl_file: /etc/sysctl.conf
    state: present
    reload: true
    ignoreerrors: true
  loop:
    - net.ipv4.conf.all.rp_filter
    - net.ipv4.conf.default.rp_filter
  notify: Flush ipv4 route table

- name: "3.3.8 | PATCH | Ensure source routed packets are not accepted"
  block:
    - name: "3.3.8 | IPv4 settings"
      ansible.posix.sysctl:
        name: "{{ item }}"
        value: '0'
        sysctl_set: true
        sysctl_file: /etc/sysctl.conf
        state: present
        reload: true
        ignoreerrors: true
      loop:
        - net.ipv4.conf.all.accept_source_route
        - net.ipv4.conf.default.accept_source_route
      notify: Flush ipv4 route table

    - name: "3.3.8 | IPv6 settings"
      ansible.posix.sysctl:
        name: "{{ item }}"
        value: '0'
        sysctl_set: true
        sysctl_file: /etc/sysctl.conf
        state: present
        reload: true
        ignoreerrors: true
      when: ipv6_disable == 'sysctl'
      loop:
        - net.ipv6.conf.all.accept_source_route
        - net.ipv6.conf.default.accept_source_route
      notify: Flush ipv6 route table

- name: "3.3.9 | PATCH | Ensure suspicious packets are logged"
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: '1'
    sysctl_set: true
    sysctl_file: /etc/sysctl.conf
    state: present
    reload: true
    ignoreerrors: true
  loop:
    - net.ipv4.conf.all.log_martians
    - net.ipv4.conf.default.log_martians
  notify: Flush ipv4 route table

- name: "3.3.10 | PATCH | Ensure tcp syn cookies is enabled"
  ansible.posix.sysctl:
    name: net.ipv4.tcp_syncookies
    value: '1'
    sysctl_set: true
    sysctl_file: /etc/sysctl.conf
    state: present
    reload: true
    ignoreerrors: true
  notify: Flush ipv4 route table

- name: "3.3.11 | PATCH | Ensure IPv6 router advertisements are not accepted"
  when:
    - ipv6_required
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: '0'
    sysctl_set: true
    sysctl_file: /etc/sysctl.conf
    state: present
    reload: true
    ignoreerrors: true
  loop:
    - net.ipv6.conf.all.accept_ra
    - net.ipv6.conf.default.accept_ra
  notify: Flush ipv6 route table