---

- name: "6.2.1.1.1 | PATCH | Ensure journald service is enabled and active"
  ansible.builtin.systemd:
    name: systemd-journald.service
    masked: false
    state: started

- name: "6.2.1.1.2 | PATCH | Ensure journald log file access is configured"
  block:
    - name: "6.2.1.1.2 | Default file permissions"
      ansible.builtin.file:
        path: /usr/lib/tmpfiles.d/systemd.conf
        mode: 'g-wx,o-rwx'

    - name: "6.2.1.1.2 | Check for override file"
      ansible.builtin.stat:
        path: /etc/tmpfiles.d/systemd.conf
      register: discovered_tmpfile_override

    - name: "6.2.1.1.2 | If override file check for journal"
      when: discovered_tmpfile_override.stat.exists
      ansible.builtin.shell: grep -E 'z /var/log/journal/%m/system.journal \d*' /usr/lib/tmpfiles.d/systemd.conf
      changed_when: false
      failed_when: discovered_journald_fileperms_override.rc not in [ 0, 1 ]
      register: discovered_journald_fileperms_override

    - name: "6.2.1.1.2 | Warning if override found"
      when:
        - discovered_tmpfile_override.stat.exists
        - discovered_journald_fileperms_override.stdout | length > 0
      ansible.builtin.debug:
        msg: "Warning!! - tmpfiles override found /usr/lib/tmpfiles.d/systemd.conf affecting journald files please confirm matches site policy"


- name: "6.2.1.1.3 | PATCH | Ensure journald log file rotation is configured"
  block:
    - name: "6.2.1.1.3 | Add file"
      ansible.builtin.template:
        src: etc/systemd/journald.conf.d/rotation.conf.j2
        dest: /etc/systemd/journald.conf.d/rotation.conf
        owner: root
        group: root
        mode: 'g-wx,o-rwx'
      notify: Restart journald

    - name: "6.2.1.1.3 | comment out current entries"
      ansible.builtin.replace:
        path: /etc/systemd/journald.conf
        regexp: "{{ item }}"
        replace: '#\1'
      loop:
        - '^(\s*SystemMaxUse\s*=.*)'
        - '^(\s*SystemKeepFree\s*=.*)'
        - '^(\s*RuntimeMaxUse\s*=)'
        - '^(\s*RuntimeKeepFree\s*=.*)'
        - '^(\s*MaxFileSec\s*=.*)'
      notify: Restart journald

- name: "6.2.1.1.4 | PATCH | Ensure journald ForwardToSyslog is disabled"
  block:
    - name: "6.2.1.1.4 | Add file"
      ansible.builtin.template:
        src: etc/systemd/journald.conf.d/forwardtosyslog.conf.j2
        dest: /etc/systemd/journald.conf.d/forwardtosyslog.conf
        owner: root
        group: root
        mode: 'g-wx,o-rwx'
      notify: Restart journald

    - name: "6.2.1.1.4 | comment out current entries"
      ansible.builtin.replace:
        path: /etc/systemd/journald.conf
        regexp: ^(\s*ForwardToSyslog)
        replace: '#\1'
      notify: Restart journald

- name: "6.2.1.1.5 | PATCH | Ensure journald Storage is configured"
  block:
    - name: "6.2.1.1.5 | Add file"
      ansible.builtin.template:
        src: etc/systemd/journald.conf.d/storage.conf.j2
        dest: /etc/systemd/journald.conf.d/storage.conf
        owner: root
        group: root
        mode: 'g-wx,o-rwx'
      notify: Restart journald

    - name: "6.2.1.1.5 | comment out current entries"
      ansible.builtin.replace:
        path: /etc/systemd/journald.conf
        regexp: ^(?i)(\s*storage=)
        replace: '#\1'
      notify: Restart journald

- name: "6.2.1.1.6 | PATCH | Ensure journald Compress is configured"
  block:
    - name: "6.2.1.1.6 | Add file"
      ansible.builtin.template:
        src: etc/systemd/journald.conf.d/storage.conf.j2  # Added to the same file as 6.2.1.1.5
        dest: /etc/systemd/journald.conf.d/storage.conf
        owner: root
        group: root
        mode: 'g-wx,o-rwx'
      notify: Restart journald

    - name: "6.2.1.1.6 | comment out current entries"
      ansible.builtin.replace:
        path: /etc/systemd/journald.conf
        regexp: ^(?i)(\s*compress=)
        replace: '#\1'
      notify: Restart journald

- name: "6.2.2.1 | PATCH | Ensure access to all logfiles has been configured"
  block:
    - name: "6.2.2.1 | find files"
      ansible.builtin.shell: find /var/log/ -type f -exec ls {} \;
      changed_when: false
      failed_when: false
      register: discovered_system_logfiles

    - name: "6.2.2.1 | change permissions"
      when:
        - discovered_system_logfiles.stdout_lines is defined
        - item != "/var/log/btmp"
        - item != "/var/log/utmp"
        - item != "/var/log/wtmp"
        - item != "/var/log/lastlog"
      ansible.builtin.file:
        path: "{{ item }}"
        mode: 'u-x,g-wx,o-rwx'
      loop: "{{ discovered_system_logfiles.stdout_lines }}"

    - name: "6.2.2.1 | change permissions"
      ansible.builtin.file:
        path: "{{ item }}"
        mode: 'ug-x,o-wx'
      with_fileglob:
        - "/var/log/*tmp"
        - "/var/log/lastlog*"
        - "/var/log/sssd*"
        - "/var/log/SSSD*"