---

- name: "SECTION | 1.2 | Configure Package Repositories and Updated"
  ansible.builtin.import_tasks:
    file: 1.2.yml
  when: section_1_2

- name: "SECTION | 1.5 | Configure Additional Process Hardening"
  ansible.builtin.import_tasks:
    file: 1.5.yml
  when: section_1_5

- name: "SECTION | 1.6 | Command Line Warning Banners"
  ansible.builtin.import_tasks:
    file: 1.6.yml
  when: section_1_6

- name: "SECTION | 1.7 | Configure GNOME Display Manager"
  ansible.builtin.import_tasks:
    file: 1.7.yml
  when: section_1_7