call each sections main here
have this get executed by the main playbook

reinstall core services (pam, ssh, etc.)

- name: "CIS Benchmark | prelims"
  ansible.builtin.import_tasks:
    file: prelim.yml

- name: "CIS Benchmark | section 1"
  ansible.builtin.import_tasks:
    file: cis_sections/section_1/main.yml

- name: "CIS Benchmark | section 3"
  ansible.builtin.import_tasks:
    file: cis_sections/section_3/main.yml

- name: "CIS Benchmark | section 5"
  ansible.builtin.import_tasks:
    file: cis_sections/section_5/main.yml

- name: "CIS Benchmark | section 6"
  ansible.builtin.import_tasks:
    file: cis_sections/section_6/main.yml

- name: "CIS Benchmark | section 7"
  ansible.builtin.import_tasks:
    file: cis_sections/section_7/main.yml

- name: ClamAV
  ansible.builtin.import_tasks: 
    file: clamav.yml

- name: SSH
  ansible.builtin.import_tasks:
    file: ssh.yml

- name: AIDE
  ansible.builtin.import_tasks:
    file: aide.yml