---
#for 1.5
- name: PRELIM | AUDIT | Discover dconf systemdb
  ansible.builtin.shell: grep system-db /etc/dconf/profile/user | cut -d ':' -f2
  changed_when: false
  failed_when: prelim_dconf_system_db.rc not in [ 0, 1 ]
  register: prelim_dconf_system_db

#for 3.1
- name: PRELIM | AUDIT | Wireless adapter pre-requisites
  when:
    - ubtu22cis_rule_3_1_2
    - not system_is_container
  tags: always
  block:
    - name: PRELIM | AUDIT | Discover is wirelss adapter on system
      ansible.builtin.shell: find /sys/class/net/*/ -type d -name wireless
      changed_when: false
      failed_when: prelim_wireless_adapters_exist.rc not in [ 0, 1 ]
      register: prelim_wireless_adapters_exist

    - name: PRELIM | PATCH | Install Network-Manager | if wireless adapter present
      when:
        - ubtu22cis_install_network_manager
        - prelim_wireless_adapters_exist.rc == 0
        - "'network-manager' not in ansible_facts.packages"
      ansible.builtin.package:
        name: network-manager
        state: present

#for 5.2
- name: PRELIM | PATCH | Find all sudoers files.
  tags: always
  ansible.builtin.shell: "find /etc/sudoers /etc/sudoers.d/ -type f ! -name '*~' ! -name '*.*'"
  changed_when: false
  failed_when: false
  check_mode: false
  register: prelim_sudoers_files

#for 5.4
- name: PRELIM | AUDIT | Gather UID 0 accounts other than root
  tags:
    - always
  ansible.builtin.shell: "cat /etc/passwd | awk -F: '($3 == 0 && $1 != \"root\") {i++;print $1 } END {exit i}'"
  changed_when: false
  check_mode: false
  register: prelim_uid_zero_accounts_except_root

#5.4
- name: PRELIM | AUDIT | Interactive Users
  tags: always
  ansible.builtin.shell: >
    grep -E -v '^(root|halt|sync|shutdown)' /etc/passwd | awk -F: '(!index($7, "sbin/nologin") && $7 != "/bin/nologin" && $7 != "/bin/false" && $7 != "/dev/null") { print $1 }'
  changed_when: false
  register: prelim_interactive_usernames

#for 5.4 and 7.2
- name: "PRELIM | Parse /etc/passwd"
  tags:
    - always
  block:
    - name: "PRELIM | Parse /etc/passwd | Get /etc/password contents"
      ansible.builtin.command: cat /etc/passwd
      changed_when: false
      check_mode: false
      register: prelim_passwd_file_audit

    - name: "PRELIM | Parse /etc/passwd | Split passwd entries"
      ansible.builtin.set_fact:
        ubu22_passwd: "{{ prelim_passwd_file_audit.stdout_lines | map('regex_replace', ld_passwd_regex, ld_passwd_yaml) | map('from_yaml') | list }}"

      with_items: "{{ prelim_passwd_file_audit.stdout_lines }}"
      vars:
        ld_passwd_regex: >-
          ^(?P<id>[^:]*):(?P<password>[^:]*):(?P<uid>[^:]*):(?P<gid>[^:]*):(?P<gecos>[^:]*):(?P<dir>[^:]*):(?P<shell>[^:]*)
        ld_passwd_yaml: |  # pragma: allowlist secret
          id: >-4
              \g<id>
          password: >-4
              \g<password>
          uid: \g<uid>
          gid: \g<gid>
          gecos: >-4
              \g<gecos>
          dir: >-4
              \g<dir>
          shell: >-4
              \g<shell>

#for 7.2
- name: PRELIM | AUDIT | Interactive User accounts home directories
  tags: always
  ansible.builtin.shell: >
    grep -E -v '^(root|halt|sync|shutdown)' /etc/passwd | awk -F: '(!index($7, "sbin/nologin") && $7 != "/bin/nologin" && $7 != "/bin/false" && $7 != "/dev/null") { print $6 }'
  changed_when: false
  register: prelim_interactive_users_home


