---
- name: Copy SSHD Config
  copy:
    src: sshd_config
    dest: /etc/ssh/sshd_config
    backup: yes

- name: OpenSSHd - Start and enable sshd
  ansible.builtin.systemd:
    name: sshd
    enabled: yes
    state: restarted
    masked: no