---
# backups
# change passwords
# make user
# audit users
# firewall
# passwords again

#Ran as root
- name: Initial Playbook | RIT CCDC
  hosts: all
  tasks:
     - name: Add blueteam user
       ansible.builtin.user: 
         name: blueteam
         state: present
         shell: /bin/bash
         groups: "blueteam sudo wheel adm"
       ignore_errors: yes

      - name: Add key to blueteam user
        ansible.posix.authorized_key:
          user: blueteam
          state: present
          key: "{{ lookup('file', '/opt/inventory/id_ed25519.pub') }}"

      - name: Install Common Packages
        apt:
          name: "{{ item }}"
          state: present
        with_items:
          - "vim"
          - "curl"
          - "iptables"
          - "git"
          - "python3-pip"
          - "snoopy"
  roles:
    - firewall
    - audit