---

# The CIS Control wants IPv6 disabled if not in use.
# We are using the ipv6_required to specify if you have IPv6 in use
- name: "3.1.1 | PATCH | Ensure IPv6 status is identified"
  block:
    - name: "3.1.1 | refresh"
      ansible.builtin.set_fact:
        sysctl_update: true
        flush_ipv6_route: true

    - name: "3.1.1 | disable"
      ansible.builtin.debug:
        msg: "Control being set via Handler 'update sysctl' which writes to /etc/sysctl.d/60-disable_ipv6.conf"
  when:
    - rule_3_1_1
    - not ipv6_required

- name: "3.1.2 | PATCH | Ensure wireless interfaces are disabled"
  block:
    - name: "3.1.2 | Check for network-manager tool"
      ansible.builtin.command: nmcli radio wifi
      changed_when: false
      failed_when: false
      check_mode: false
      register: discovered_wifi_status
      when: "'network-manager' in ansible_facts.packages"

    - name: "3.1.2 | Disable wireless if network-manager installed"
      ansible.builtin.command: nmcli radio all off
      changed_when: discovered_nmcli_radio_off.rc == 0
      register: discovered_nmcli_radio_off
      when:
        - "'network-manager' in ansible_facts.packages"
        - "'enabled' in discovered_wifi_status.stdout"

    - name: "3.1.2 | Warn about wireless if network-manager not installed"
      ansible.builtin.debug:
        msg: "Warning!! You need to disable wireless interfaces manually since network-manager is not installed"
      when: "'network-manager' not in ansible_facts.packages"  
  when:
    - rule_3_1_2
    - discover_wireless_adapters.rc == 0

- name: "3.1.3 | PATCH | Ensure bluetooth services are not in use"
  ansible.builtin.package:
    name: bluez
    state: absent
  when: rule_3_1_3
